// V3.7.3 — Template copy dictionary.
//
// Every user-facing string the template needs lives in CMS SiteSettings
// .templateCopy as a flat key→text map. The renderer never invents text:
// a missing key either omits an optional element or is flagged by QA.
//
// `REQUIRED_COPY_KEYS` are blocking: a site cannot reach HUMAN_REVIEW_READY
// while they are absent. Everything else is optional furniture.

export type TemplateCopy = Record<string, string>;

/** Default Russian dictionary written once at generation time. After that it
 *  is ordinary CMS data — owned by the editor, preserved across regen. */
export const DEFAULT_TEMPLATE_COPY_RU: TemplateCopy = {
  // entity kind labels
  'entity.service': 'Услуга',
  'entity.project': 'Объект',
  'entity.news': 'Новость',
  'entity.vacancy': 'Вакансия',
  'entity.product': 'Продукт',
  'entity.default': 'Материал',
  // collection names used when a page/section lacks its own heading
  'collection.services': 'Услуги',
  'collection.projects': 'Объекты',
  'collection.news': 'Новости',
  'collection.vacancies': 'Вакансии',
  'collection.products': 'Каталог',
  // back-navigation labels per collection kind
  'back.services': 'Все услуги',
  'back.projects': 'Все объекты',
  'back.news': 'Все новости',
  'back.vacancies': 'Все вакансии',
  'back.products': 'Весь каталог',
  // view-all link: {name} = the section's own CMS heading
  'viewAll.template': 'Все {name}',
  'navSubmenu.all': 'Все — {name}',
  // provenance link
  'source.link': 'Источник ↗',
  // pagination
  'pager.aria': 'Страницы',
  'pager.prev': '← Назад',
  'pager.next': 'Вперёд →',
  'collection.empty': 'На этой странице нет элементов.',
  // mobile menu
  'menu.open': 'Меню',
  'menu.close': 'Закрыть',
  'menu.aria': 'Главное меню',
  'hero.aria': 'Начало',
  // 404
  'notFound.title': 'Страница не найдена',
  'notFound.lede': 'По адресу «{path}» ничего нет.',
  'notFound.home': '← На главную',
  'nav.home': 'Главная',
  'notFound.code': '404',
  // detail-view furniture
  'detail.galleryAria': 'Галерея',
  'detail.specsAria': 'Характеристики',
  'detail.factsAria': 'Факты о компании',
  'detail.category': 'Категория',
  'detail.location': 'Локация',
  'detail.prevAria': 'Предыдущий объект',
  'detail.nextAria': 'Следующий объект',
  'detail.indexTemplate': '{label} {i} / {n}',
  'detail.openCta': 'Открыть объект →',
  'detail.pageCta': 'Страница объекта →',
  'detail.galleryAlt': '{title} — фото {n}',
  'detail.entityIndexAlt': '{title} — {n}',
  'back.default': 'Назад',
  'about.directions': 'Направления',
  'about.companyHeading': 'Компания',
  'about.factsAria': 'Факты о компании',
  'about.founded': 'Основана',
  'about.team': 'Команда',
  'about.unp': 'УНП',
  'about.address': 'Адрес',
  'contacts.heading': 'Контакты',
  'contacts.phone': 'Телефон',
  'contacts.email': 'Email',
  'contacts.address': 'Адрес',
  'contacts.hours': 'Режим работы',
  'chapter.label': 'Глава {n}',
  // certificates & lightbox
  'certs.openAria': 'Открыть документ: {name}',
  'certs.docUntitled': 'Документ {n}',
  'lightbox.zoomFit': 'Уместить',
  'lightbox.zoomIn': 'Увеличить',
  'lightbox.openOriginal': 'Открыть оригинал',
  'lightbox.download': 'Скачать',
  'lightbox.close': 'Закрыть',
  'lightbox.prev': '← Пред.',
  'lightbox.next': 'След. →',
  'services.figureAria': 'Иллюстрация активной услуги',
  'footer.aria': 'Нижняя навигация',
  'a11y.skipLink': 'Перейти к содержимому',
  // construction-template furniture
  'menu.openAria': 'Открыть меню',
  'media.noPhoto': 'Без фотографии',
  'media.noPhotoTitled': '{title} — без фотографии',
  'back.home': '← Назад к главной',
  'cta.primary': 'Связаться',
  'vacancy.requirements': 'Требования',
  'vacancy.conditions': 'Условия',
  'vacancy.contacts': 'Контакты',
  'vacancy.empty': 'Нет открытых вакансий',
  'detail.otherItems': 'Другие материалы',
  'detail.viewItem': 'Смотреть {name} →',
  'detail.more': 'Подробнее',
  'detail.projectMore': 'Подробнее об объекте',
  'section.faq': 'Часто задаваемые вопросы',
  'section.reviews': 'Отзывы',
  'section.process': 'Как мы работаем',
  'section.pricing': 'Цены',
  'section.about': 'О компании',
  'section.portfolio': 'Портфолио',
  'section.processLede': 'Этапы работы над проектом — от первого контакта до результата.',
  'footer.navigation': 'Навигация',
  'footer.procurement': 'Отдел закупок',
  'footer.tenders': 'Тендеры',
  'footer.tenderCta': 'Пригласить на тендер →',
  'footer.copyright': '© {years} {name}. Все права защищены.',
  'footer.copyrightLegal': '© {years} {name}. УНП {unp}. Все права защищены.',
  // industrial-template furniture (CMS-owned editorial copy)
  'cta.request': 'Оставить заявку',
  'cta.discuss': 'Обсудить проект',
  'cta.viewProjects': 'Смотреть проекты',
  'cta.eyebrow': 'Есть проект?',
  'cta.heading.pre': 'Давайте создадим ',
  'cta.heading.em': 'основу',
  'cta.heading.post': ' вместе.',
  'cta.contactUs': 'Связаться с нами',
  'hero.statsServices': '{n} компетенций',
  'hero.statsProjects': '{n} объектов',
  'hero.index': '{n} / {total}',
  'section.numberedEyebrow': '{n} / {name}',
  'intro.title.pre': 'Надёжная основа для ',
  'intro.title.em': 'смелых',
  'intro.title.post': ' идей.',
  'about.more': 'Больше о компании',
  'viewAll.default': 'Смотреть все',
  'viewAll.projects': 'Смотреть все объекты →',
  'viewAll.catalog': 'Смотреть каталог →',
  'cta.discussTask': 'Обсудить задачу →',
  'cta.discussProject': 'Обсудить ваш проект',
  'contacts.reception': 'Приёмная / Заказчикам',
  'contacts.tenderInvite': 'Пригласить на тендер',
  'contacts.tenderSubject': 'Приглашение на тендер',
  'services.footerNote': 'Работаем с заказчиками по договору',
  'industrial.servicesEyebrow': '02 / Что мы делаем',
  'industrial.servicesTitle': 'Работаем на ваш результат.',
  'industrial.servicesText': 'Практическая экспертиза для сложных задач в строительстве, инфраструктуре и инженерии.',
  'industrial.servicesLink': 'Наши компетенции',
  'industrial.projectsEyebrow': '03 / Объекты',
  'industrial.projectsTitle': 'Проекты с весом.',
  'industrial.projectsText': 'Избранные объекты, выполненные с вниманием к деталям.',
  'industrial.projectsLink': 'Все объекты',
  'industrial.newsEyebrow': '04 / Новости',
  'industrial.newsTitle': 'Новости компании.',
  'industrial.newsLink': 'Все новости',
  'footer.companyTagline': 'Генеральный подрядчик для инфраструктурных, промышленных и коммерческих объектов.',
  'footer.tagline': 'Строим среду для жизни и бизнеса',
  'footer.copyrightShort': '© {year} {name}',
  'contacts.office': 'Главный офис',
  'contacts.responseTime': 'Ответим в течение двух рабочих дней.',
  'contacts.eyebrow': 'Контакты / Начнём здесь',
  'contacts.heroTitle': 'Обсудим следующий шаг.',
  'contacts.heroText': 'Расскажите, что вы строите, на каком этапе находитесь и каким видите результат.',
  'collection.eyebrow': 'Раздел / {name}',
  'collection.servicesTitle': 'Компетенции, которым можно доверять.',
  'collection.servicesText': 'Практическая экспертиза для сложных задач в строительстве.',
  'collection.servicesName': 'компетенции',
  'collection.projectsTitle': 'Проекты с весом.',
  'collection.projectsText': 'Избранные проекты.',
  'collection.projectsName': 'проекты',
  'collection.newsTitle': 'Новости компании.',
  'collection.newsText': 'Новости, идеи и истории.',
  'collection.newsName': 'новости',
  'notFound.eyebrow': 'Ошибка',
  'notFound.detail': 'Запрашиваемый контент не существует.',
  'detail.eyebrow': '{kind} / {category}',
  'detail.approachEyebrow': 'Продуманный подход',
  'detail.approachTitle.pre': 'Сложное становится ',
  'detail.approachTitle.em': 'выполнимым.',
  'page.eyebrow': 'Страница',
  'vacancies.eyebrow': 'Компания / Вакансии',
  'vacancies.title': 'Работа, которая имеет значение.',
  'vacancies.text': 'Присоединяйтесь к команде.',
  'vacancy.fullTime': 'Полный день',
  'form.name': 'Имя',
  'form.email': 'Рабочая почта',
  'form.message': 'Чем можем помочь?',
  'form.submit': 'Отправить запрос',
};

/** Keys whose absence blocks acceptance — the site visibly breaks without
 *  them (navigation, entity framing, empty-state honesty). */
export const REQUIRED_COPY_KEYS = [
  'menu.open', 'menu.close', 'menu.aria', 'hero.aria',
  'notFound.title', 'notFound.lede', 'notFound.home',
  'source.link', 'viewAll.template', 'back.services', 'back.projects',
  'back.news', 'back.products', 'pager.aria', 'pager.prev', 'pager.next',
  'collection.empty',
];

/** Merge strategy: generated defaults fill only absent keys — existing CMS
 *  values (editor-owned after manualModifiedAt) are never overwritten. */
export function mergeTemplateCopy(existing: TemplateCopy | null | undefined): TemplateCopy {
  return { ...DEFAULT_TEMPLATE_COPY_RU, ...(existing || {}) };
}
