import type { TemplateManifest } from '../types.js';

export const constructionModernV1Manifest: TemplateManifest = {
  id: 'construction-modern-v1',
  name: 'Construction Modern v1',
  fallbackPrimaryColor: '#C8A464',
  supportedSectionTypes: [
    'hero',
    'about',
    'services',
    'projects',
    'news',
    'vacancies',
    'contacts',
    'cta',
    'certificates',
    'partners',
    'equipment',
    'gallery',
    'page_teaser',
    'collection_teaser',
    'text',
    'image',
    'gallery_block',
  ],
  sectionRendererMap: {
    about: 'AboutSection',
    services: 'ServiceList',
    projects: 'ProjectList',
    news: 'NewsList',
    vacancies: 'VacancyList',
    contacts: 'CallToAction',
    cta: 'CallToAction',
    certificates: 'GenericSection',
    partners: 'GenericSection',
    equipment: 'GenericSection',
    gallery: 'GenericSection',
    page_teaser: 'GenericPageTeaser',
    collection_teaser: 'GenericCollectionTeaser',
    text: 'GenericContentSection',
    image: 'GenericContentSection',
    gallery_block: 'GenericContentSection',
  },
  collectionRendererMap: {
    news: 'NewsList',
    projects: 'ProjectList',
    services: 'ServiceList',
    vacancies: 'VacancyList',
    certificates: 'GenericCollection',
    partners: 'GenericCollection',
    equipment: 'GenericCollection',
  },
  pageRenderer: 'PageView',
};
