import type { TemplateManifest } from '../types.js';

export const constructionModernV1Manifest: TemplateManifest = {
  id: 'construction-modern-v1',
  name: 'Construction Modern v1',
  fallbackPrimaryColor: '#C8A464',
  supportedSectionTypes: [
    'hero',
    'about',
    'services',
    'projects',
    'news',
    'vacancies',
    'products',
    'contacts',
    'cta',
    'certificates',
    'partners',
    'equipment',
    'gallery',
    'page_teaser',
    'collection_teaser',
    'text',
    'image',
    'gallery_block',
  ],
  sectionRendererMap: {
    about: 'AboutSection',
    services: 'ServiceList',
    projects: 'ProjectList',
    news: 'NewsList',
    vacancies: 'VacancyList',
    contacts: 'CallToAction',
    cta: 'CallToAction',
    certificates: 'GenericSection',
    partners: 'GenericSection',
    equipment: 'GenericSection',
    gallery: 'GenericSection',
    page_teaser: 'GenericPageTeaser',
    collection_teaser: 'GenericCollectionTeaser',
    text: 'GenericContentSection',
    image: 'GenericContentSection',
    gallery_block: 'GenericContentSection',
  },
  collectionRendererMap: {
    news: 'NewsList',
    projects: 'ProjectList',
    services: 'ServiceList',
    vacancies: 'VacancyList',
    products: 'ProductList',
    certificates: 'GenericCollection',
    partners: 'GenericCollection',
    equipment: 'GenericCollection',
  },
  // Homepage collection previews — each homepageSections[] entry carries its
  // own `limit`; these are the defaults when the section leaves it empty.
  // Defaults preserve pre-contract visuals (services/products showed 6,
  // news/vacancies 3; projects previously showed ALL — now capped at the
  // shared default page size).
  collectionSections: {
    services: { defaultLimit: 6, supportsLimit: true },
    projects: { defaultLimit: 6, supportsLimit: true },
    news: { defaultLimit: 3, supportsLimit: true },
    vacancies: { defaultLimit: 3, supportsLimit: true },
    products: { defaultLimit: 6, supportsLimit: true },
  },
  pageRenderer: 'PageView',
};
