'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { usePathname } from 'next/navigation'
import { ArrowRight, ArrowUpRight, ChevronDown, Mail, MapPin, Menu, Phone, X } from 'lucide-react'

export type SiteImage = { src: string; alt: string }
export type Service = { slug: string; number: string; title: string; text: string; image: SiteImage }
export type Project = { slug: string; category: string; title: string; location: string; year: string; image: SiteImage }
export type НовостиItem = { slug: string; date: string; category: string; title: string; excerpt: string }

export const services: Service[] = [
  { slug: 'civil-engineering', number: '01', title: 'Гражданское строительство', text: 'Земляные работы, инженерные сети и инфраструктура — от обследования до сдачи объекта.', image: { src: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1200&q=85', alt: 'Строительная бригада на объекте' } },
  { slug: 'industrial-construction', number: '02', title: 'Промышленное строительство', text: 'Сложные производственные объекты, спроектированные для требовательных процессов.', image: { src: 'https://images.unsplash.com/photo-1565008447742-97f6f38c985c?auto=format&fit=crop&w=1200&q=85', alt: 'Стальной каркас здания' } },
  { slug: 'commercial-buildings', number: '03', title: 'Коммерческие здания', text: 'Эффективные и гибкие пространства для арендаторов, операторов и инвесторов.', image: { src: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=85', alt: 'Фасад современного коммерческого здания' } },
  { slug: 'maintenance', number: '04', title: 'Реконструкция и сервис', text: 'Продлеваем срок службы и ценность существующих объектов, сохраняя рабочий ритм бизнеса.', image: { src: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=1200&q=85', alt: 'Специалист осматривает строительную конструкцию' } },
]

export const projects: Project[] = [
  { slug: 'north-terminal', category: 'Инфраструктура', title: 'Расширение Северного терминала', location: 'Минск, Беларусь', year: '2025', image: { src: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=1600&q=85', alt: 'Строительство транспортного узла на окраине Минска' } },
  { slug: 'atlas-logistics', category: 'Промышленность', title: 'Логистический кампус «Атлас»', location: 'Брест, Беларусь', year: '2024', image: { src: 'https://images.unsplash.com/photo-1565793298595-6a879b1d9492?auto=format&fit=crop&w=1200&q=85', alt: 'Строительство логистического склада в Брестской области' } },
  { slug: 'riverside-offices', category: 'Коммерция', title: 'Офисы у реки', location: 'Гродно, Беларусь', year: '2024', image: { src: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=85', alt: 'Интерьер нового делового центра в Гродно' } },
]

export const news: НовостиItem[] = [
  { slug: 'new-framework-agreement', date: '18.06.2025', category: 'Компания', title: 'Новое рамочное соглашение укрепляет инфраструктуру региона', excerpt: 'Многолетнее партнёрство поддержит устойчивые проекты в сфере региональной мобильности.' },
  { slug: 'safety-week-2025', date: '04.06.2025', category: 'Команда', title: 'Безопасность — это дисциплина, а не лозунг', excerpt: 'Ежегодная неделя безопасности превращает ежедневные наблюдения в практические улучшения на объектах.' },
  { slug: 'energy-ready-sites', date: '21.05.2025', category: 'Идеи', title: 'Строительные площадки готовы к энергетическому переходу', excerpt: 'Как ранняя координация помогает реализовать электрификацию и низкоуглеродное строительство.' },
]

const Arrow = () => <ArrowUpRight aria-hidden="true" />

export type NavigationItem = { label: string; href?: string; children?: NavigationItem[]; external?: boolean }

const navigation: NavigationItem[] = [
  { label: 'Главная', href: '/' },
  { label: 'О компании', href: '/about', children: [{ label: 'О нас', href: '/about' }, { label: 'История', href: '/content' }, { label: 'Сертификаты', href: '/content' }, { label: 'Лицензии', href: '/content' }] },
  { label: 'Услуги', href: '/services', children: [{ label: 'Генеральный подряд', href: '/services/industrial-construction', children: [{ label: 'Фундаменты и нулевой цикл', href: '/services/civil-engineering' }, { label: 'Монолитные работы', href: '/services/industrial-construction' }] }, { label: 'Реконструкция', href: '/services/maintenance' }, { label: 'Благоустройство', href: '/services/commercial-buildings' }] },
  { label: 'Объекты', href: '/projects' },
  { label: 'Новости', href: '/news' },
  { label: 'Вакансии', href: '/vacancies' },
  { label: 'Контакты', href: '/contact' },
]

function isItemActive(item: NavigationItem, pathname: string) { return !!item.href && (pathname === item.href || (item.href !== '/' && pathname.startsWith(`${item.href}/`)) || item.children?.some((child) => isItemActive(child, pathname))) }

function NavigationBranch({ item, pathname, mobile = false, onNavigate }: { item: NavigationItem; pathname: string; mobile?: boolean; onNavigate: () => void }) {
  const active = isItemActive(item, pathname)
  if (!item.children?.length) return <Link href={item.href ?? '#'} className={active ? 'is-current' : ''} target={item.external ? '_blank' : undefined} rel={item.external ? 'noreferrer' : undefined} onClick={onNavigate}>{item.label}</Link>
  return <details className={`nav-group ${active ? 'is-active' : ''}`} open={mobile ? active : undefined}><summary aria-label={`${item.label} подменю`}>{item.href ? <Link href={item.href} onClick={onNavigate}>{item.label}</Link> : <span>{item.label}</span>}<ChevronDown aria-hidden="true" /></summary><div className="nav-menu">{item.children.map((child) => <NavigationBranch key={`${item.label}-${child.label}`} item={child} pathname={pathname} mobile={mobile} onNavigate={onNavigate} />)}</div></details>
}

export function Header() {
  const [open, setOpen] = useState(false)
  const [mobileMenu, setMobileMenu] = useState(false)
  const pathname = usePathname()
  useEffect(() => { const handleKey = (event: KeyboardEvent) => { if (event.key === 'Escape') { setOpen(false); setMobileMenu(false) } }; window.addEventListener('keydown', handleKey); return () => window.removeEventListener('keydown', handleKey) }, [])
  const closeMenus = () => { setOpen(false); setMobileMenu(false) }
  return <header className="site-header"><div className="container header-inner"><Link href="/" className="wordmark" onClick={closeMenus}><span className="wordmark-mark">N</span><span>МИНСКСТРОЙ<span className="wordmark-sub">/ ПОДРЯДЧИК</span></span></Link><nav className={`main-nav ${open ? 'is-open' : ''}`} aria-label="Основная навигация">{navigation.slice(0, 6).map((item) => <NavigationBranch key={item.label} item={item} pathname={pathname} onNavigate={closeMenus} />)}</nav><div className="header-actions"><a className="header-phone" href="tel:+375173004567">+375 (17) 300-45-67</a><Link href="/contact" className="nav-contact">Оставить заявку <Arrow /></Link><button className="menu-toggle" aria-label={mobileMenu ? 'Закрыть меню' : 'Открыть меню'} aria-expanded={mobileMenu} onClick={() => setMobileMenu(!mobileMenu)}>{mobileMenu ? <X /> : <Menu />}<span>Меню</span></button></div></div><div className={`mobile-nav ${mobileMenu ? 'is-open' : ''}`} aria-hidden={!mobileMenu}><div className="container mobile-nav-inner"><p className="eyebrow">Навигация</p>{navigation.map((item) => <NavigationBranch key={`mobile-${item.label}`} item={item} pathname={pathname} mobile onNavigate={closeMenus} />)}<a className="mobile-phone" href="tel:+375173004567">+375 (17) 300-45-67</a></div></div></header>
}

export function SectionIntro({ eyebrow, title, text, href, linkLabel = 'Смотреть все' }: { eyebrow: string; title: string; text?: string; href?: string; linkLabel?: string }) { return <div className="section-intro"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{text && <p className="intro-copy">{text}</p>}{href && <Link className="text-link" href={href}>{linkLabel} <Arrow /></Link>}</div> }
export type HeroProps = { company: string; eyebrow?: string; title: React.ReactNode; text: string; image: SiteImage; primaryCta: { label: string; href: string }; secondaryCta?: { label: string; href: string }; metadata?: string[]; index?: string }

export function Hero({ company, eyebrow, title, text, image, primaryCta, secondaryCta, metadata = [], index = '01 / 04' }: HeroProps) { return <section className="hero"><div className="hero-image"><img src={image.src} alt={image.alt} /></div><div className="hero-rule" /><div className="container hero-content"><div className="hero-copy"><p className="eyebrow hero-eyebrow">{eyebrow ?? company}</p><h1>{title}</h1><p className="hero-description">{text}</p><div className="hero-actions"><Link className="button button-accent" href={primaryCta.href}>{primaryCta.label} <Arrow /></Link>{secondaryCta && <Link className="text-link hero-secondary" href={secondaryCta.href}>{secondaryCta.label} <Arrow /></Link>}</div></div><div className="hero-meta">{metadata.map((item) => <span key={item}>{item}</span>)}</div></div><div className="hero-index">{index}</div></section> }
export function ServiceCard({ service }: { service: Service }) { return <Link href={`/services/${service.slug}`} className="service-card"><div className="service-image"><img src={service.image.src} alt={service.image.alt} /></div><div className="service-meta"><span>{service.number}</span><h3>{service.title}</h3><ArrowRight /></div><p>{service.text}</p></Link> }
export function ProjectCard({ project, featured = false }: { project: Project; featured?: boolean }) { return <Link href={`/projects/${project.slug}`} className={`project-card ${featured ? 'project-card-featured' : ''}`}><div className="project-image"><img src={project.image.src} alt={project.image.alt} /></div><div className="project-caption"><div><p className="eyebrow">{project.category} / {project.year}</p><h3>{project.title}</h3></div><p>{project.location}</p></div></Link> }
const footerGroups = [{ title: 'Навигация', links: [['О компании', '/about'], ['Компетенции', '/services'], ['Проекты', '/projects'], ['Новости', '/news']] }, { title: 'Компания', links: [['Вакансии', '/vacancies'], ['Контакты', '/contact'], ['Стандарты', '/content']] }]

export function Footer() { return <footer className="footer"><div className="container footer-lead"><div><Link href="/" className="wordmark"><span className="wordmark-mark">N</span><span>МИНСКСТРОЙ<span className="wordmark-sub">/ ПОДРЯДЧИК</span></span></Link><p className="footer-note">Генеральный подрядчик для инфраструктурных, промышленных и коммерческих объектов.</p></div><div className="footer-contact"><p className="eyebrow">Главный офис</p><p>ул. Кальварийская, 42<br />220004 Минск / Беларусь</p><a href="mailto:info@minskstroy.by">info@minskstroy.by</a></div><div className="footer-contact"><p className="eyebrow">Телефон</p><a href="tel:+31102345678">+375 (17) 300-45-67</a><p>Пн–Пт / 08:00–17:30</p></div></div><div className="container footer-links">{footerGroups.map((group) => <div key={group.title}><p className="eyebrow">{group.title}</p>{group.links.map(([label, href]) => <Link key={href} href={href}>{label}</Link>)}</div>)}<div><p className="eyebrow">Соцсети</p><a href="https://www.linkedin.com/company/nord-contractor" target="_blank" rel="noreferrer">LinkedIn</a><a href="https://www.instagram.com/nord.contractor" target="_blank" rel="noreferrer">Instagram</a></div></div><div className="container footer-bottom"><span>© 2025 Группа компаний «МинскСтрой»</span><span>Конфиденциальность / Cookies</span><span>Строим среду для жизни и бизнеса</span></div></footer> }
export function ContactStrip() { return <section className="contact-strip"><div className="container contact-inner"><div><p className="eyebrow">Есть проект?</p><h2>Давайте создадим<br /><em>основу</em> вместе.</h2></div><Link className="button button-dark" href="/contact">Связаться с нами <Arrow /></Link></div></section> }
export function SiteShell({ children }: { children: React.ReactNode }) { return <><Header />{children}<Footer /></> }
export function PageHero({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <section className="page-hero"><div className="container"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{text}</p></div></section> }
export function ContactDetails() { return <div className="contact-details"><div><MapPin /><p>ул. Кальварийская, 42<br />220004 Минск<br />Республика Беларусь</p></div><div><Phone /><p><a href="tel:+31102345678">+375 (17) 300-45-67</a><br />Пн–Пт, 08:00–17:30</p></div><div><Mail /><p><a href="mailto:info@minskstroy.by">info@minskstroy.by</a><br />Ответим в течение двух рабочих дней.</p></div></div> }

export function HomePage() { return <SiteShell><Hero company="МИНСКСТРОЙ" eyebrow="Генподрядчик / Минск / Работаем с 1987 года" title={<>Создаём то, что<br /><em>движет</em> Беларусь.</>} text="Строим инфраструктуру, промышленные объекты и пространства, которые работают на развитие страны." image={{ src: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=2200&q=90', alt: 'Башенный кран на строительной площадке' }} primaryCta={{ label: 'Обсудить проект', href: '/contact' }} secondaryCta={{ label: 'Смотреть проекты', href: '/projects' }} metadata={['Инфраструктура', 'Минск, Беларусь', 'Проектирование / Строительство']} /><main><section className="intro-section"><div className="container intro-grid"><p className="eyebrow">01 / О компании</p><div><h2>Надёжная основа для <em>смелых</em> идей.</h2><p className="large-copy">МинскСтрой — независимый генеральный подрядчик для проектов, где важны сложность, преемственность и ответственность.</p><Link className="text-link" href="/about">Больше о МинскСтрой <Arrow /></Link></div></div></section><section className="section-block"><div className="container"><SectionIntro eyebrow="02 / Что мы делаем" title="Работаем на ваш результат." text="От первого технико-экономического обоснования до ввода в эксплуатацию — одна команда работает вместе с вами." href="/services" linkLabel="Наши компетенции" /><div className="services-grid">{services.map((service) => <ServiceCard key={service.slug} service={service} />)}</div></div></section><section className="dark-section"><div className="container"><SectionIntro eyebrow="03 / Избранные проекты" title="Доказательство — в результате." href="/projects" linkLabel="Смотреть все проекты" /><div className="projects-grid">{projects.map((project, index) => <ProjectCard key={project.slug} project={project} featured={index === 0} />)}</div></div></section><section className="capabilities"><div className="container capability-grid"><div><p className="eyebrow">04 / Почему МинскСтрой</p><h2>One team.<br /><em>Full</em> responsibility.</h2></div><div className="capability-list">{['Подрядчик с первого дня', 'Комплексное проектирование', 'Безопасность в основе', 'Предсказуемая сдача'].map((item, i) => <div key={item}><span>0{i + 1}</span><h3>{item}</h3><p>Чёткие решения, прямое общение и ответственная команда с первого дня.</p></div>)}</div></div></section><section className="news-section"><div className="container"><SectionIntro eyebrow="05 / Latest" title="From the field." href="/news" /><div className="news-list">{news.map((item) => <Link className="news-row" key={item.slug} href={`/news/${item.slug}`}><span>{item.date}</span><span>{item.category}</span><h3>{item.title}</h3><Arrow /></Link>)}</div></div></section><ContactStrip /></main></SiteShell> }

export function CollectionPage({ type }: { type: 'services' | 'projects' | 'news' }) { const isServices = type === 'services'; const isProjects = type === 'projects'; return <SiteShell><PageHero eyebrow={`Раздел / ${type === 'services' ? 'компетенции' : type === 'projects' ? 'проекты' : 'новости'}`} title={isServices ? 'Компетенции, которым можно доверять.' : isProjects ? 'Проекты с весом.' : 'Новости МинскСтрой.'} text={isServices ? 'Практическая экспертиза для сложных задач в строительстве, инфраструктуре и инженерии.' : isProjects ? 'Избранные проекты, выполненные с вниманием к деталям, контролем и взглядом в будущее.' : 'Новости, идеи и истории наших проектов и людей.'} /><main className="collection-page"><div className="container">{isServices ? <div className="services-grid">{services.map((service) => <ServiceCard key={service.slug} service={service} />)}</div> : isProjects ? <div className="projects-grid collection-projects">{projects.map((project) => <ProjectCard key={project.slug} project={project} featured />)}</div> : <div className="news-list">{news.map((item) => <Link className="news-row" key={item.slug} href={`/news/${item.slug}`}><span>{item.date}</span><span>{item.category}</span><h3>{item.title}</h3><Arrow /></Link>)}</div>}</div></main><ContactStrip /></SiteShell> }

export function DetailPage({ kind, slug }: { kind: 'service' | 'project' | 'news'; slug: string }) { const service = services.find((item) => item.slug === slug) ?? services[0]; const project = projects.find((item) => item.slug === slug) ?? projects[0]; const article = news.find((item) => item.slug === slug) ?? news[0]; const title = kind === 'service' ? service.title : kind === 'project' ? project.title : article.title; const text = kind === 'service' ? service.text : kind === 'project' ? `${project.category}: объект в ${project.location}, завершён в ${project.year} году.` : article.excerpt; const image = kind === 'service' ? service.image : kind === 'project' ? project.image : projects[0].image; return <SiteShell><PageHero eyebrow={`${kind === 'project' ? 'Объект' : kind === 'service' ? 'Услуга' : 'Новость'} / ${kind === 'news' ? article.date : kind === 'project' ? project.location : 'Компетенции МинскСтрой'}`} title={title} text={text} /><main className="detail-page"><div className="container detail-grid"><div className="detail-media"><img src={image.src} alt={image.alt} /></div><article><p className="eyebrow">Продуманный подход</p><h2>Сложное становится <em>выполнимым.</em></h2><p className="large-copy">Каждый проект начинается с точного вопроса и общего понимания результата. Наши специалисты объединяют дисциплину планирования, техническую глубину и практический опыт, чтобы превратить замысел в работающий объект.</p><p>Мы работаем прозрачно, заранее решаем проблемы и учитываем людей, которые создают и используют наши объекты.</p><Link className="button button-accent" href="/contact">Обсудить проект <Arrow /></Link></article></div></main><ContactStrip /></SiteShell> }

export function AboutPage() { return <SiteShell><PageHero eyebrow="Компания / О компании" title="Работаем с ответственностью." text="Мы строительная и инженерная компания, которая мыслит как собственник и опирается на практический опыт работы на объекте." /><main className="about-page"><div className="container stat-grid"><div><strong>38</strong><span>лет опыта</span></div><div><strong>420</strong><span>специалистов в команде</span></div><div><strong>96%</strong><span>повторных партнёрств</span></div></div><div className="container detail-grid about-detail"><div><p className="eyebrow">Наш подход к работе</p><h2>Хороший результат — это <em>слаженная</em> работа.</h2></div><div><p className="large-copy">Мы объединяем точность инженерного подхода с практическим знанием людей, которые работают на объекте.</p><p>Наша модель проста: внимание руководителей, открытая коммуникация, ответственные команды и точность в деталях.</p></div></div></main><ContactStrip /></SiteShell> }

export function VacanciesPage() { return <SiteShell><PageHero eyebrow="Компания / Вакансии" title="Работа, которая имеет значение." text="Присоединяйтесь к команде, которая делает каждый объект безопаснее, надёжнее и лучше." /><main className="collection-page"><div className="container vacancies-list">{['Руководитель проекта — гражданское строительство','Ведущий инженер на объекте — промышленное строительство','Планировщик работ — крупные проекты','Инженер-стажёр — свободная заявка'].map((role) => <Link key={role} className="vacancy-row" href="/vacancies/open-application"><span>Минск / Полный день</span><h2>{role}</h2><Arrow /></Link>)}</div></main><ContactStrip /></SiteShell> }

export function ContactPage() { return <SiteShell><PageHero eyebrow="Контакты / Начнём здесь" title="Обсудим следующий шаг." text="Расскажите, что вы строите, на каком этапе находитесь и каким видите результат." /><main className="contact-page"><div className="container contact-page-grid"><ContactDetails /><form className="contact-form"><label>Имя<input required name="name" /></label><label>Рабочая почта<input required type="email" name="email" /></label><label>Чем можем помочь?<textarea required name="message" rows={5} /></label><button className="button button-accent" type="submit">Отправить запрос <Arrow /></button></form></div></main></SiteShell> }

export function GenericPage() { return <SiteShell><PageHero eyebrow="Content / Page" title="A clear path through complexity." text="A flexible content template for the stories, standards and principles that shape the way we work." /><main className="generic-page"><div className="container narrow-copy"><h2>Useful information, plainly presented.</h2><p className="large-copy">This page is ready for CMS content, policy text or a longer editorial story. Replace the placeholder copy with tenant-specific content without changing the layout system.</p><p>Use structured headings, short paragraphs and related links to keep important information accessible to every visitor.</p></div></main><ContactStrip /></SiteShell> }
